# Generated by Django 5.0.3 on 2024-03-30 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('from_user_id', models.CharField(max_length=64, verbose_name='from user id')),
                ('to_user_id', models.CharField(max_length=64, verbose_name='to user id')),
                ('content', models.CharField(max_length=2048, verbose_name='content')),
                ('media', models.CharField(max_length=512, verbose_name='media')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date time')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('mail', models.CharField(max_length=128, verbose_name='email')),
                ('login', models.CharField(max_length=64, verbose_name='login')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('avatar', models.CharField(max_length=256, verbose_name='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('messages', models.ManyToManyField(to='server.message')),
                ('users', models.ManyToManyField(to='server.user')),
            ],
        ),
    ]
