# Generated by Django 5.0.3 on 2024-04-17 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('from_user_id', models.CharField(max_length=64, verbose_name='from user id')),
                ('content', models.CharField(max_length=2048, verbose_name='content')),
                ('media', models.CharField(max_length=512, verbose_name='media')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date time')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(to='server.message'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
                ('login', models.CharField(max_length=64, verbose_name='login')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('avatar', models.CharField(max_length=256, verbose_name='avatar')),
                ('is_online', models.BooleanField(default=True, verbose_name='IS ONLINE')),
                ('chats', models.ManyToManyField(to='server.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to='server.user'),
        ),
    ]
