# Generated by Django 5.0.3 on 2024-05-07 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('owner_id', models.CharField(max_length=256, verbose_name='owner')),
                ('avatar', models.CharField(max_length=256, verbose_name='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='ServerChatRoom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='ServerMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('from_user_id', models.CharField(max_length=64, verbose_name='from user id')),
                ('content', models.CharField(max_length=2048, verbose_name='content')),
                ('media', models.CharField(blank=True, max_length=512, null=True, verbose_name='media')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date time')),
            ],
        ),
    ]
