# Generated by Django 5.0.3 on 2024-05-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.user', verbose_name='users'),
        ),
        migrations.AddField(
            model_name='serverchatroom',
            name='server_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server'),
        ),
        migrations.AddField(
            model_name='server',
            name='chat_rooms',
            field=models.ManyToManyField(blank=True, to='server.serverchatroom', verbose_name='chat_rooms'),
        ),
        migrations.AddField(
            model_name='serverchatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, to='server.servermessage'),
        ),
    ]
