# Generated by Django 5.0.4 on 2024-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_chat_messages_alter_user_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(max_length=512, upload_to='', verbose_name='media'),
        ),
    ]
