# Generated by Django 5.0.3 on 2024-05-09 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationLink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID_')),
                ('data', models.CharField(max_length=64, verbose_name='invitation_link_data')),
                ('server_uuid', models.CharField(max_length=64, verbose_name='server_uuid')),
            ],
        ),
    ]
