# Generated by Django 5.0.3 on 2024-04-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_user_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
