# Generated by Django 5.0.3 on 2024-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_mail_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='IS ONLINE'),
        ),
    ]
