# Generated by Django 5.0.3 on 2024-04-21 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_message_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerChatRoom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('messages', models.ManyToManyField(blank=True, to='server.message')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('owner_id', models.CharField(max_length=256, verbose_name='owner')),
                ('avatar', models.ImageField(upload_to='', verbose_name='avatar')),
                ('users', models.ManyToManyField(blank=True, to='server.user', verbose_name='users')),
                ('chat_rooms', models.ManyToManyField(to='server.serverchatroom', verbose_name='chat_rooms')),
            ],
        ),
    ]
