# Generated by Django 5.0.3 on 2024-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_invitationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermessage',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='has read'),
        ),
    ]
