# Generated by Django 5.0.3 on 2024-04-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_serverchatroom_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.CharField(max_length=512, verbose_name='media'),
        ),
    ]
