# Generated by Django 5.0.3 on 2024-05-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_servermessage_has_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermessage',
            name='has_read',
        ),
    ]
