# Generated by Django 5.0.3 on 2024-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='media'),
        ),
    ]
