# Generated by Django 5.0.3 on 2024-06-04 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_servermessage_has_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAudioRoom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('server_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server')),
            ],
        ),
    ]
