# Generated by Django 5.0.3 on 2024-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_message_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='title',
            field=models.CharField(default='test', max_length=32, verbose_name='title'),
            preserve_default=False,
        ),
    ]
