# Generated by Django 5.0.3 on 2024-06-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_serveraudioroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='audio_rooms',
            field=models.ManyToManyField(blank=True, to='server.serveraudioroom', verbose_name='audio_rooms'),
        ),
    ]
