# Generated by Django 5.0.3 on 2024-06-08 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_server_audio_rooms'),
        ('users', '0002_alter_user_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=64, verbose_name='permission title')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='description')),
                ('is_owner_perm', models.BooleanField(default=False, verbose_name='is owner permission')),
            ],
        ),
        migrations.CreateModel(
            name='ServerMember',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('user_uuid', models.CharField(max_length=32, null=True, verbose_name='APP USER UUID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
            ],
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='server',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderators', to='users.user', verbose_name='moderators'),
        ),
        migrations.AddField(
            model_name='serverchatroom',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='private?'),
        ),
        migrations.AlterField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.user', verbose_name='users'),
        ),
        migrations.AddField(
            model_name='server',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='server.servermember', verbose_name='members'),
        ),
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=17, verbose_name='name')),
                ('color', models.CharField(max_length=32, verbose_name='color')),
                ('permissions', models.ManyToManyField(to='server.permission', verbose_name='permissions')),
            ],
        ),
    ]
