# Generated by Django 5.0.3 on 2024-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_server_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='chat_rooms',
            field=models.ManyToManyField(blank=True, to='server.serverchatroom', verbose_name='chat_rooms'),
        ),
    ]
