# Generated by Django 5.0.3 on 2024-04-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_server_chat_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='servers',
            field=models.ManyToManyField(blank=True, to='server.server'),
        ),
    ]
