# Generated by Django 5.0.3 on 2024-04-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_user_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverchatroom',
            name='title',
            field=models.CharField(default='test', max_length=256, verbose_name='title'),
            preserve_default=False,
        ),
    ]
