# Generated by Django 5.0.3 on 2024-04-30 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_serverchatroom_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('from_user_id', models.CharField(max_length=64, verbose_name='from user id')),
                ('content', models.CharField(max_length=2048, verbose_name='content')),
                ('media', models.CharField(blank=True, max_length=512, null=True, verbose_name='media')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date time')),
            ],
        ),
    ]
