# Generated by Django 5.0.3 on 2024-05-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_message_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverchatroom',
            name='server_object',
            field=models.ForeignKey(default='2302f077-f01f-4767-ad51-b031bbb60b5c', on_delete=django.db.models.deletion.PROTECT, to='server.server'),
            preserve_default=False,
        ),
    ]
