# Generated by Django 5.0.3 on 2024-05-05 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_serverchatroom_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverchatroom',
            name='server_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server'),
        ),
    ]
