# Generated by Django 5.0.3 on 2024-05-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_alter_serverchatroom_server_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
        migrations.RemoveField(
            model_name='user',
            name='servers',
        ),
    ]
