# Generated by Django 5.0.3 on 2024-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_remove_chat_messages_remove_chat_users_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.user', verbose_name='users'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
