# Generated by Django 5.0.3 on 2024-05-07 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
                ('login', models.CharField(max_length=64, verbose_name='login')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('avatar', models.CharField(max_length=256, verbose_name='avatar')),
                ('is_online', models.BooleanField(default=True, verbose_name='IS ONLINE')),
                ('chats', models.ManyToManyField(blank=True, to='chats.chat')),
                ('servers', models.ManyToManyField(blank=True, to='server.server')),
            ],
        ),
    ]
